AWSTemplateFormatVersion: "2010-09-09"
Description: A Sample template
Resources:
    EC2-Instance-1:
        Type: AWS::EC2::Instance
        Properties:
            DisableApiTermination: true
            ImageId: ami-067d1e60475437da2
            InstanceType: t2.micro
            KeyName: vockey
            SubnetId: subnet-0992254e038f2f3d9
            SecurityGroupIds: !ref Security-Group
            UserData: 
              !Base64: |
                #!/bin/bash
                dnf install -y httpd
                systemctl enable httpd
                systemctl start httpd
                echo '<html><h1>Hello From Your Web Server!</h1></html>' > /var/www/html/index.html    
    Security-Group:
        Type: AWS::EC2::SecurtiyGroup
        Properties:
            GroupDescription: Lab-security-group-description
            GroupName: Lab-security-group
            SecurityGroupIngress: 
                - IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: "0.0.0.0/0"
            VpcId: vpc-0c06fedf842be2e9d